// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: service.proto

package modelrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BaseModelInterfaceClient is the client API for BaseModelInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseModelInterfaceClient interface {
	// Make prediction based on user request
	Predict(ctx context.Context, in *ModelInterfaceRequest, opts ...grpc.CallOption) (*ModelInterfaceResponse, error)
}

type baseModelInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseModelInterfaceClient(cc grpc.ClientConnInterface) BaseModelInterfaceClient {
	return &baseModelInterfaceClient{cc}
}

func (c *baseModelInterfaceClient) Predict(ctx context.Context, in *ModelInterfaceRequest, opts ...grpc.CallOption) (*ModelInterfaceResponse, error) {
	out := new(ModelInterfaceResponse)
	err := c.cc.Invoke(ctx, "/mlserving.BaseModelInterface/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseModelInterfaceServer is the server API for BaseModelInterface service.
// All implementations must embed UnimplementedBaseModelInterfaceServer
// for forward compatibility
type BaseModelInterfaceServer interface {
	// Make prediction based on user request
	Predict(context.Context, *ModelInterfaceRequest) (*ModelInterfaceResponse, error)
	mustEmbedUnimplementedBaseModelInterfaceServer()
}

// UnimplementedBaseModelInterfaceServer must be embedded to have forward compatible implementations.
type UnimplementedBaseModelInterfaceServer struct {
}

func (UnimplementedBaseModelInterfaceServer) Predict(context.Context, *ModelInterfaceRequest) (*ModelInterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedBaseModelInterfaceServer) mustEmbedUnimplementedBaseModelInterfaceServer() {}

// UnsafeBaseModelInterfaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseModelInterfaceServer will
// result in compilation errors.
type UnsafeBaseModelInterfaceServer interface {
	mustEmbedUnimplementedBaseModelInterfaceServer()
}

func RegisterBaseModelInterfaceServer(s grpc.ServiceRegistrar, srv BaseModelInterfaceServer) {
	s.RegisterService(&BaseModelInterface_ServiceDesc, srv)
}

func _BaseModelInterface_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseModelInterfaceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlserving.BaseModelInterface/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseModelInterfaceServer).Predict(ctx, req.(*ModelInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseModelInterface_ServiceDesc is the grpc.ServiceDesc for BaseModelInterface service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseModelInterface_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlserving.BaseModelInterface",
	HandlerType: (*BaseModelInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _BaseModelInterface_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
