# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='base_model.proto',
    package='mlserving',
    syntax='proto3',
    serialized_options=b'\n\017mlserving.modelP\001',
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x10\x62\x61se_model.proto\x12\tmlserving\"\x95\x01\n\x15ModelInterfaceRequest\x12>\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32-.mlserving.ModelInterfaceRequest.DetailsEntry\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x16ModelInterfaceResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x64\n\x12\x42\x61seModelInterface\x12N\n\x07Predict\x12 .mlserving.ModelInterfaceRequest\x1a!.mlserving.ModelInterfaceResponseB\x13\n\x0fmlserving.modelP\x01\x62\x06proto3'
)

_MODELINTERFACEREQUEST_DETAILSENTRY = _descriptor.Descriptor(
    name='DetailsEntry',
    full_name='mlserving.ModelInterfaceRequest.DetailsEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='mlserving.ModelInterfaceRequest.DetailsEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='value', full_name='mlserving.ModelInterfaceRequest.DetailsEntry.value', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=b'8\001',
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=135,
    serialized_end=181,
)

_MODELINTERFACEREQUEST = _descriptor.Descriptor(
    name='ModelInterfaceRequest',
    full_name='mlserving.ModelInterfaceRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='details', full_name='mlserving.ModelInterfaceRequest.details', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='data', full_name='mlserving.ModelInterfaceRequest.data', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[_MODELINTERFACEREQUEST_DETAILSENTRY, ],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=32,
    serialized_end=181,
)

_MODELINTERFACERESPONSE = _descriptor.Descriptor(
    name='ModelInterfaceResponse',
    full_name='mlserving.ModelInterfaceResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='data', full_name='mlserving.ModelInterfaceResponse.data', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=183,
    serialized_end=221,
)

_MODELINTERFACEREQUEST_DETAILSENTRY.containing_type = _MODELINTERFACEREQUEST
_MODELINTERFACEREQUEST.fields_by_name['details'].message_type = _MODELINTERFACEREQUEST_DETAILSENTRY
DESCRIPTOR.message_types_by_name['ModelInterfaceRequest'] = _MODELINTERFACEREQUEST
DESCRIPTOR.message_types_by_name['ModelInterfaceResponse'] = _MODELINTERFACERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelInterfaceRequest = _reflection.GeneratedProtocolMessageType('ModelInterfaceRequest', (_message.Message,), {

    'DetailsEntry': _reflection.GeneratedProtocolMessageType('DetailsEntry', (_message.Message,), {
        'DESCRIPTOR': _MODELINTERFACEREQUEST_DETAILSENTRY,
        '__module__': 'base_model_pb2'
        # @@protoc_insertion_point(class_scope:mlserving.ModelInterfaceRequest.DetailsEntry)
    })
    ,
    'DESCRIPTOR': _MODELINTERFACEREQUEST,
    '__module__': 'base_model_pb2'
    # @@protoc_insertion_point(class_scope:mlserving.ModelInterfaceRequest)
})
_sym_db.RegisterMessage(ModelInterfaceRequest)
_sym_db.RegisterMessage(ModelInterfaceRequest.DetailsEntry)

ModelInterfaceResponse = _reflection.GeneratedProtocolMessageType('ModelInterfaceResponse', (_message.Message,), {
    'DESCRIPTOR': _MODELINTERFACERESPONSE,
    '__module__': 'base_model_pb2'
    # @@protoc_insertion_point(class_scope:mlserving.ModelInterfaceResponse)
})
_sym_db.RegisterMessage(ModelInterfaceResponse)

DESCRIPTOR._options = None
_MODELINTERFACEREQUEST_DETAILSENTRY._options = None

_BASEMODELINTERFACE = _descriptor.ServiceDescriptor(
    name='BaseModelInterface',
    full_name='mlserving.BaseModelInterface',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=223,
    serialized_end=323,
    methods=[
        _descriptor.MethodDescriptor(
            name='Predict',
            full_name='mlserving.BaseModelInterface.Predict',
            index=0,
            containing_service=None,
            input_type=_MODELINTERFACEREQUEST,
            output_type=_MODELINTERFACERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_BASEMODELINTERFACE)

DESCRIPTOR.services_by_name['BaseModelInterface'] = _BASEMODELINTERFACE

# @@protoc_insertion_point(module_scope)
