# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from framework.interfaces.base.api import base_model_pb2 as base__model__pb2


class BaseModelInterfaceStub(object):
    """
    Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
            '/mlserving.BaseModelInterface/Predict',
            request_serializer=base__model__pb2.ModelInterfaceRequest.SerializeToString,
            response_deserializer=base__model__pb2.ModelInterfaceResponse.FromString,
        )


class BaseModelInterfaceServicer(object):
    """
    Service
    """

    def Predict(self, request, context):
        """Make prediction based on user request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BaseModelInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Predict': grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=base__model__pb2.ModelInterfaceRequest.FromString,
            response_serializer=base__model__pb2.ModelInterfaceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'mlserving.BaseModelInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BaseModelInterface(object):
    """
    Service
    """

    @staticmethod
    def Predict(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlserving.BaseModelInterface/Predict',
                                             base__model__pb2.ModelInterfaceRequest.SerializeToString,
                                             base__model__pb2.ModelInterfaceResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
