kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data-storage
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: rabbitmq-data-storage
spec:
  storageClassName: rabbitmq-data-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data-storage"