kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data
spec:
  storageClassName: rabbitmq-data-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi